Documentation:
  Enable: false

Metrics/BlockLength:
  Enable: true
  Exclude:
    - spec/**/*

Lint/AmbiguousBlockAssociation:
  Enable: false

Metrics/LineLength:
  Max: 105

AllCops:
  Exclude:
  - '**/Rakefile'
  - 'vendor/**/*'
  - 'spec/fixtures/**/*'
  - 'spec/*_helper.rb'
  - 'tmp/**/*'
  - 'bin/**/*'
  - 'db/**/*'
  - 'config/**/*'
  - 'script/**/*'
  - 'test/**/*'
  - 'app/v1/controllers/users/*'
  - 'lib/tasks/*'